# Generated by Django 6.0.4 on 2026-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='distraction_sites',
            field=models.TextField(default='instagram.com,youtube.com,facebook.com,tiktok.com,twitter.com'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='productive_sites',
            field=models.TextField(default='chatgpt.com,claude.ai,reddit.com,coursera.org,notion.so,github.com'),
        ),
    ]
