# Generated by Django 6.0.4 on 2026-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_distraction_sites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='playlist_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pomodoro_break_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pomodoro_work_minutes',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='distraction_sites',
            field=models.TextField(default='instagram.com,youtube.com,facebook.com,tiktok.com,twitter.com,reddit.com'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='productive_sites',
            field=models.TextField(default='chatgpt.com,claude.ai,khanacademy.org,coursera.org,notion.so,github.com'),
        ),
    ]
